version: "3"
services:
  resource_service:
    build:
      context: ./MicroserviceResourceService
    ports:
      - "8081:8080"
    depends_on:
      - db
  
  song_service:
    build:
      context: ./MicroserviceSongService
    ports:
      - "8082:8080"
    depends_on:
      - db

  db:
    image: postgres:11.1-alpine
    container_name: "postgres-container"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: